### ISSUE TITLE
avast warning

### ISSUE THREAD

**Issue by mankowitz** [ulties/voyager-cheatsheet#4]
hey, 

I use avast antivirus on windows 10, and when I go to https://voyager-cheatsheet.ulties.com it gives me a warning and won't let me see the page. Avast isn't telling me why.

Thanks.

**Comment by marktopper** [comment]
Hmm.
That sounds weird.

Can you access [this site](http://cheats.jesse-obrien.ca/)?
Cause I basically justed forked them and added Voyager methods

EDIT: However, I have plans to rebuild the entire site from scratch soon.
Hopefully, that will help.

**Comment by marktopper** [comment]
I have just scanned the website, and there was nothing.
Result: http://www.urlvoid.com/scan/voyager-cheatsheet.ulties.com/

Closing for now, please let me know if this still happens after updating Avast.
